# Generated by Django 4.2.6 on 2023-11-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_subscriptions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='News.category'),
        ),
    ]
